In [2]:
import pickle
word_embedding_path = "/home/madm/Documents/EANN_recon/data/weibo/w2v.pickle"
w2v = pickle.load(open(word_embedding_path, 'rb+'), encoding='ISO-8859-1')
len(w2v)

4626

In [9]:
import pickle

w2v = pickle.load(open(word_embedding_path, 'rb+'), encoding='ISO-8859-1')

import numpy as np

def get_W(word_vecs, k=32):
    word_idx_map = dict()
    W = np.zeros(shape=(len(word_vecs) + 1, k), dtype='float32')
    W[0] = np.zeros(k, dtype='float32')    
    for idx, word in enumerate(word_vecs):
        W[idx] = word_vecs[word]
        word_idx_map[word] = idx
    return W, word_idx_map

W, word_idx_map = get_W(w2v)
W.shape,len(word_idx_map)


((4627, 32), 4626)

In [12]:
import pickle

w2v = pickle.load(open(word_embedding_path, 'rb+'), encoding='ISO-8859-1')


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [2]:
import pickle
word_embedding_path = "/home/madm/Documents/EANN_recon/data/weibo/word_embedding.pickle"
word_embedding = pickle.load(open(word_embedding_path, 'rb+'), encoding='ISO-8859-1')
word_embedding

[array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.34330672,  0.09084792, -0.11461054, ...,  0.33812454,
         -0.2189882 ,  0.43914253],
        [ 0.16631643,  0.06407708, -0.9694754 , ...,  0.12508143,
          0.6176479 , -0.26249015],
        ...,
        [-0.03084401,  0.18639795, -0.02950158, ..., -0.1074877 ,
         -0.0098281 , -0.2075982 ],
        [ 0.07506293,  0.16626914,  0.07161643, ..., -0.2443795 ,
          0.01616616,  0.09720282],
        [-0.09524532, -0.22186401, -0.13890591, ..., -0.11209083,
         -0.22221242,  0.08968041]], dtype=float32),
 {},
 {'耀': 1,
  '挂': 2,
  '唬': 3,
  '怀': 4,
  '涉': 5,
  '谈': 6,
  '伊': 7,
  '随': 8,
  '茂': 9,
  '抗': 10,
  '脖': 11,
  '料': 12,
  '萘': 13,
  '洞': 14,
  '造': 15,
  '咣': 16,
  '錢': 17,
  '瞥': 18,
  '瘤': 19,
  '礦': 20,
  '黝': 21,
  '般': 22,
  '作': 23,
  '河': 24,
  '欲': 25,
  '侵': 26,
  '临': 27,
  '銷': 28,
  '然': 29,
  '疹': 30,
  '吸': 31,
  '场': 32,
  '宽': 33,

In [18]:
import pickle

c = open('/home/madm/Documents/EANN_recon/data/weibo/test_id.pickle','rb')
data = pickle.load(c)
print(data)

{'3924406688174231': 27, '3913825189070405': 15, '3795450035622703': 14, '3554213017672034': 27, '3906467960248126': 9, '3506598830132592': 18, '3924451458163220': 27, '3928604578890978': 25, '3899675628956011': 13, '3912794653108552': 13, '3910502293529954': 10, '3911988595478332': 25, '3909450614302124': 18, '3765749334030099': 27, '3563050151616103': 9, '3919944259229682': 18, '3682640596610862': 19, '3836883430073657': 12, '3670603720065006': 27, '3490117287436856': 9, '3915187918582187': 17, '3926550330086727': 13, '3554970932194213': 9, '3925490052070623': 13, '3487357100032369': 25, '3920011728937273': 9, '3764951749411918': 27, '3929142367825553': 25, '3754974880664048': 17, '3521080176318410': 18, '3920002141360762': 14, '3501422018867300': 10, '3475964787233120': 9, '3651353941886440': 9, '3919930187720867': 13, '3858773682267066': 18, '3919876815165491': 10, '3602487389432799': 13, '3653708506355501': 27, '3912983954065698': 12, '3894592208246721': 13, '3859537817933738': 18

In [19]:
import pickle
word_embedding_path = "/home/madm/Documents/EANN_recon/data/weibo/w2v.pickle"
word_embedding = pickle.load(open(word_embedding_path, 'rb+'), encoding='ISO-8859-1')
word_embedding

{'耀': array([ 0.34330672,  0.09084792, -0.11461054,  0.340821  ,  0.7586583 ,
        -0.00354594, -0.6846231 , -0.31817648,  0.12614137,  0.4019267 ,
         0.00910563,  0.19139731, -0.36410564,  0.225091  ,  0.1379466 ,
        -0.40822133, -0.38063404,  0.17977916, -0.10085351,  0.27195254,
         0.06618848, -0.04161769, -0.10894711,  0.30633682,  0.09047063,
        -0.04720515, -0.61741525,  0.5991251 , -0.13544238,  0.33812454,
        -0.2189882 ,  0.43914253], dtype=float32),
 '挂': array([ 0.16631643,  0.06407708, -0.9694754 , -0.28977594,  0.08631775,
         0.07767463, -0.43079558,  0.81968594,  0.11267024,  0.03155328,
         0.2742497 , -0.00390452,  0.1772085 ,  0.32807425,  0.1163568 ,
         0.6856986 , -0.14598283, -0.26246879,  0.32363668,  0.11438536,
        -0.19085792,  0.67649686, -0.70002943,  0.8035548 ,  0.10122051,
         0.26615524,  0.80413485, -0.14151314, -0.06067622,  0.12508143,
         0.6176479 , -0.26249015], dtype=float32),
 '唬': array(

In [47]:
map_id={1: 0}
event = 23

if event not in map_id:
    map_id[event] = len(map_id)
    event = map_id[event]
else:
    event = map_id[event]

map_id,event

({1: 0, 23: 1}, 1)

In [42]:
import numpy as np
label = [1,3,5]
test = np.array(label, dtype=np.int)
test

array([1, 3, 5])

In [48]:
word_vector_path = '/home/madm/Documents/EANN_recon/data/weibo/word_embedding.pickle'
f = open(word_vector_path, 'rb')
weight = pickle.load(f) 
W, W2, word_idx_map, vocab, max_len = weight[0], weight[1], weight[2], weight[3], weight[4]
len(vocab)

4640

In [16]:
import torch
a = torch.arange(1,41)
a.view(20,2)
a.size()

torch.Size([40])

In [26]:
import torch
b = torch.zeros((20,2))
b.size(),b

(torch.Size([20, 2]),
 tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]))

In [28]:
import torch
c = torch.zeros((20))
c.size(),c

(torch.Size([20]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [29]:
c.squeeze()

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
c.shape

torch.Size([20])